version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket samtestpackage --output-template-file packaged.yaml

artifacts:
  type: zip
  files:
    - template.yaml
    - packaged.yaml